### ISSUE TITLE
how do i setup i3-focus?

### ISSUE THREAD

**Issue by plexigras** [pbogut/dotfiles#1]

**Comment by pbogut** [comment]
Do you want to use it with vim or tmux?
Currently I'm not using tmux, so I'm using it with neovim only, but it should be possible to set it up for vim and tmux. It is based on window title, so you have to set up correct win title for neovim / tmux.

Let me know whith what you want to use it then I will give you more details.

**Comment by plexigras** [comment]
I want to use the i3 shortcuts inside nvim and tmux.

It would also be nice to be able to have the movement commands but i have no idea how to set that up either.

**Comment by pbogut** [comment]
For tmux you need this in tmux.conf:
```
# set title
set -g set-titles on
set -g set-titles-string '#{pane_current_command} tmux #{session_id}:#{window_index}:#{pane_index}'
```

For vim inside tmux you can use `christoomey/vim-tmux-navigator` plugin.

If you want to use neovim without tmux you need this in your vimrc:
```
augroup set_title_group
    autocmd!
    autocmd BufEnter * call s:set_title_string()
augroup END
function! s:set_title_string()
  let file = expand('%:~')
  if file == ""
    let file = substitute(getcwd(),$HOME,'~', 'g')
  endif
  if empty($SSH_CLIENT) && empty($SSH_TTY)
    let &titlestring = $USER . '@' . hostname() . ":nvim:" . substitute($NVIM_LISTEN_ADDRESS, '/tmp/nvim\(.*\)\/0$', '\1', 'g') . ":" . l:file
  else
    let &titlestring = $USER . '@' . hostname() . ":nvim:" . l:file
  endif
endfunction
let &titlestring = $USER . '@' . hostname() . ":nvim:" . substitute($NVIM_LISTEN_ADDRESS, '/tmp/nvim\(.*\)\/0$', '\1', 'g') . ":" . substitute(getcwd(),$HOME,'~', 'g')
set title
```

and

```
" i3focus
function! local#i3focus#switch(comando, vim_comando)
  " clear mapping echo
  let oldw = winnr()
  silent exe 'wincmd ' . a:vim_comando
  let neww = winnr()
  if oldw == neww
    silent! exe '!~/.scripts/i3-focus.py ' . a:comando . ' --skip-vim > /dev/null'
  endif
endfunction
```

Maybe there is easier way, dunno.

In i3-focus.py there is also some keys configuration, You may want to change vim_dir to `c-h`, `c-l` etc, if you using vim in tmux, this will be 'clicked' when in tmux. 

You need to install `neovim-remote`: `pip install neovim-remote` and i3 bindings for python `pip install i3-py`.

I think that's it, but I may be wrong. I've set it up long time ago and I could forget bout something.
